#!/bin/bash
set -e

source $(dirname $0)/version

ARCH=${ARCH:?"ARCH not set"}
SUFFIX=""
[ "${ARCH}" != "amd64" ] && SUFFIX="_${ARCH}"

cd $(dirname $0)/..
mkdir -p dist/artifacts rootfs
cd rootfs

mkdir -p usr/bin

cp ../package/start-cni-driver.sh usr/bin/start-cni-driver.sh
cp ../bin/rancher-cni-driver usr/bin/rancher-cni-driver

tar cvzf ../dist/artifacts/rancher-cni-driver-${ARCH}-${VERSION}.tar.gz .

echo "Built rancher-cni-driver-${ARCH}-${VERSION}.tar.gz"
